### PR TITLE
Remove notification- prefixed icons

### PR DESCRIPTION
**Pull request by newhoa**
Remove most of the notification- prefixed icons. The only mention of these names seems to be in Ubuntu's notify-osd, which, while still in the repository has not been used in Ubuntu since 14.04, and isn't used in any of the Ubuntu flavors. notify-osd is not in the Fedora, OpenSuse, etc reposities.

Remaining icons in the notification folder were moved to the status folder. notification folder was removed, entries removed from index.theme.

nm-applet seemed to use a few of the Network notification- icons, so those were left.

Updated krb- icons to use newer elementary status symbols.

Added gnome-lockscreen symlink which is used for nm-applet notification when connecting to or disconnecting from a VPN.

### CODE REVIEW

**Review by ochosi — APPROVED** [review]
Generally speaking, I like supporting projects that are still in ubuntu's repos, because there may be users of it out there. Also, in Xfce one can easily replace xfce4-notifyd with another notification daemon.

Since you're doing pretty much all of the heavy lifting in this theme nowadays though, I'll leave this decision up to you.

**Comment by newhoa** [comment]
You're right about supporting them, I suppose especially if it was intended to be supported by the theme in the first place. Plus, I forgot about Ubuntu Unity, which does use notify-osd by default.

However, after testing, notify-osd seems to not work so great. Either notify-osd has not been updated, or apps are using some other standard/protocol. It doesn't work with a lot of applications (nm-applet/NetworkManager, many music players, pidgin, battery, printing), even default Ubuntu Unity apps. And a lot of times when it does work, instead of showing the popup bubble, it annoyingly shows a Gtk Dialog with Yes, No, and Cancel buttons. And on top of that, notify-osd sometimes uses FreeDesktop names, sometimes its own, and sometimes not even its own (in the case of sticky keys keyboard icon which it does not provide). A bit messy.

I tested as much as I could, and added back (or newly added) what worked. Still an overall reduction since the network, messaging, etc icons aren't used.

Anyway, if this is okay it should be good to go! Thanks!

**Comment by ochosi** [comment]
Interesting. I've maintained xfce4-notifyd long enough to know that in the last 10 years nothing in the notification spec has changed and there was no need to update a daemon.
Did you install notify-osd alongside other notification daemons? I think they sometimes interfere, some of them (even xfce4-notifyd has this option) don't autostart, but instead launch when the first notification gets sent.

In any case, thanks for testing and adding back a few!

**Comment by newhoa** [comment]
> Interesting. I've maintained xfce4-notifyd long enough to know that in the last 10 years nothing in the notification spec has changed and there was no need to update a daemon. Did you install notify-osd alongside other notification daemons? I think they sometimes interfere, some of them (even xfce4-notifyd has this option) don't autostart, but instead launch when the first notification gets sent.
> 
> In any case, thanks for testing and adding back a few!

First I tried it just by uninstalling xfce4-notifyd and installing notify-osd and had issues (thought something was interfering). Then I realized Ubuntu Unity used it by default, so I thought that would give me a better or "proper" experience. So I tried the live image on desktop and laptop and still had the same issues.

I don't know enough about the notification system to know why, I was just guessing something might have changed. I did check to see if notify-osd was still being updated and they did transition to Gtk3 so maybe something went weird there? Maybe a full install of Ubuntu Unity would have been better (maybe an issue with a live environment). Not sure. Probably won't research more unless someone has an issue. I'm back to the good ol' xfce4-notifyd. :)

**Pull request merged**
