### PR TITLE
Add panel monochrome indicator/tray icons for system update

### PR DESCRIPTION
**Pull request by Mau-G**
Monochrome icons in the Xfce are preferable for system consistency. These icons are for the system updater indicator or systray. Tested with package-updater-indicator in openSUSE,  the icons can be symlinked  to support the different tools if needed.

See screenshots below:

Before:
system-updater-before

After:
system-updater-after

### CODE REVIEW

**Comment by ochosi** [comment]
Hi, thanks for those icons!
One remark, I'd prefer a normal circle for the monochrome version, simply because the current one makes me think of the sun or "weather" in general. Would you agree or mind adapting that?

The background why I never created monochrome versions of those icons was simply because I liked them to stand out a little visually from the otherwise monochrome panel (imo they "demand attention" because users shall act on them and install updates).

**Comment by Mau-G** [comment]
> Hi, thanks for those icons!
> One remark, I'd prefer a normal circle for the monochrome version, simply because the current one makes me think of the sun or "weather" in general. Would you agree or mind adapting that?

It was inspired by this tango icon but let me ping the actual designer @hellcp to borrow his brain.
update

> The background why I never created monochrome versions of those icons was simply because I liked them to stand out a little visually from the otherwise monochrome panel (imo they "demand attention" because users shall act on them and install updates).

It is a valid point worth considering for when updates are actually available. One thing to keep in mind is that the indicator is always visible in the panel so when no updates are available it is better to have a monochrome icon imo.

**Comment by Mau-G** [comment]
@ochosi I modified the "software-update-vailable" and "software-update-urgent" colored so that they would grab more attention when needed.

No update:
no_update

Update available:
update available


> One remark, I'd prefer a normal circle for the monochrome version, simply because the current one makes me think of the sun or "weather" in general. Would you agree or mind adapting that?

On a second thought I don't think it's a good idea because I noticed that it would look like the account-logged-in.svg icon. 

I do understand it kinda does look like the sun, but it's hardly confusing because the weather plug in uses a different type of icon sets. Imo it gets attention I doubt people would get confused, especially since Tango had a similar icon and old time users might be familiar with it :-). Let me know what you think.

**Comment by Mau-G** [comment]
I have a version with the "exclamation mark" inside the icon transparent that perhaps looks better.

update available alternative

**Comment by Mau-G** [comment]
@ochosi we made some new icons which are in the latest commits. Do you like these better?

No update:
system-update

Update available:
update-available

Update urgent alternative (with dot)
urgent-alternative

**Comment by ochosi** [comment]
Nice work! I like those last ones and would go with the "with dot" version, that's also in line with what the notification plugin has.

**Comment by ochosi** [comment]
I took a closer look at the SVGs and they're really aligned along the grid, which is why they're a little hazy in your screenshot.

Not sure how much experience you have with drawing icons, just let me know if you can clean that up or if you want/need me to.

Another point, I would suggest that "update-available" uses the class "success" instead of "warning" and that "update-urgent" uses the class "warning" instead of "error". Semantically that just makes more sense (and I'll probably also update the notification-new-symbolic icon to not use error anymore).

**Comment by Mau-G** [comment]
> I took a closer look at the SVGs and they're really aligned along the grid, which is why they're a little hazy in your screenshot.
> 
> Not sure how much experience you have with drawing icons, just let me know if you can clean that up or if you want/need me to.

Yes I can try  to clean that up.

> Another point, I would suggest that "update-available" uses the class "success" instead of "warning" and that "update-urgent" uses the class "warning" instead of "error". Semantically that just makes more sense (and I'll probably also update the notification-new-symbolic icon to not use error anymore).

Does this mean  to also change the color to green for "available" and yellow for "urgent"? or we can keep the same colors? 

One note on symbolic icons is that they don't seem to work properly with xfce4-status notifier-plugin, even if the option in the settings is checked.

**Comment by Mau-G** [comment]
@ochosi see  last commit please. I made a set that hope is "pixel perfect" and sharper.

I changed the color of "update available" to blue because it seems to be used for attention across the theme and because it stands out more than yellow. But can change those colors if you think they are not suitable.

software-update-no-update


software-update-available

software-update-urgent

There is also a new alternative set with *-alternative.svg. I got some feedback telling me that the main icon set was perhaps not very "elementary" so I'm offering an alternative one.

software-update-no-update-alternative

software-update-available-alternative

software-update-urgent-alternative

Please let me know what you think.

**Comment by ochosi** [comment]
Really nice work! :+1: 
I don't have the time to look into the SVGs tonight, but I can tell you I like those last three the most (the proper arrows and the blue and red dots). I would probably still go for the orange "warning" color instead of the red "error" (because semantically it makes more sense to warn the user about the importance of security updates, but they're not necessarily an error), but I'd also merge as is.

So I would suggest you clean up the branch to only contain the last three icons, possibly create a new pull-request with just that and I'll take them for a final SVG review in the coming week (having a busy weekend) and merge them in.

**Comment by Mau-G** [comment]
> So I would suggest you clean up the branch to only contain the last three icons, possibly create a new pull-request with just that and I'll take them for a final SVG review in the coming week (having a busy weekend) and merge them in.

ok I will close this one and open a new one

**Pull request closed without merging**
