### PR TITLE
Update the mime office icons (Fixes #239)

### LINKED ISSUE #239: Update office icons
Hi, I'm trying to update the office mime icons for the theme.

There are some libreoffice specific files that don't seem necessary and I am wondering how to handle them. There seems to be two different Office icons for each file type but one of them don't seem to be used. There are many of these but for this example I'm using the text/document file.

The mime type for an `.odt` file is `application/vnd.oasis.opendocument.text`.

This is what the file browsers I've tried use to get the icon. Thunar, Nemo, Pantheon, Rox, Nautilus. It's what the [OpenDocument spec](https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Documents) uses. And it seems to be what [Libreoffice uses](https://wiki.documentfoundation.org/Faq/General/036).

The elementary-xfce theme also provide a second document icon (one symlinked to the other):
`libreoffice-text`
`libreoffice-oasis-text`

When installed, Libreoffice [puts these all three of the above fives in hicolor](https://wiki.documentfoundation.org/Gallery_Icons). For `libreoffice-text` and `libreoffice-oasis-text` [they symlink these](https://github.com/qt-haiku/LibreOffice/blob/master/reportbuilder/java/org/libreoffice/report/pentaho/oasis-text.css) to `application/vnd.oasis.opendocument.text`. However, this may be for legacy sake because they don't seem to be used by the program or any file manager.

Elementary upstream provides a document file that follows the [FreeDesktop naming spec](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html), `x-office-document`, and then symlinks `vnd.oasis.opendocument.text` to that. It does not provide, even as symlinks, the `libreoffice-*` files.

I could do one of three:

- Delete them
- Replace them with the icons Libreoffice provides (they are CC-BY-SA)
- Keep them and symlink them to the upstream `x-office-document`/`vnd.oasis` document icon

I'd like to delete them since they don't seem to be used and conflict with upstream. They would be confusing to contributors who don't know what they are, and take more time to figure out or maintain.

### PR DESCRIPTION
**Pull request by newhoa**
Edit: This should be ready now. Please merge #235 before this PR (if that PR is to be accepted).

This is an update/refresh of the office mime type icons.

Pulled spreadsheet and slideshow from upstream.
Made template versions.
Made 96px versions.
Re-symlinked icons to match upstream.
Fixed incorrectly symlinked opendocument icons.
Fixed incorrectly symlinked openxmlformat icons.
Made template icons for openxmlformats.
Removed old libreoffice and openoffice specific files ([no longer used](https://wiki.documentfoundation.org/Faq/General/036) by libreoffice or openoffice).
Remade template triangle/set square ruler to match other sizes.
Applied new ruler to other text mime icons (text, gettext, etc).

Fixes #239  if changes above are okay.

---
Pictures

Modified old (left) vs new (right)
Shows updated openxml and opendocument icons and new template ruler.
modified-old-vs-new2

Removed unused icons (replaced with icons above with proper mimetype names)
deleted2

Added icons (missing sizes, etc)
added2

### CODE REVIEW

**Comment by ochosi** [comment]
@newhoa Please rebase - thanks!

**Comment by newhoa** [comment]
@ochosi Sorry for the delay on the rebase. Should be good for review now. Thanks!

**Comment by ochosi** [comment]
Actually the LibreOffice mimetype icons are consistent with the application icons we have for LO, e.g. https://github.com/shimmerproject/elementary-xfce/blob/master/elementary-xfce/apps/64/libreoffice-writer.svg

What's the rationale for changing the mimetype icons?

**Comment by newhoa** [comment]
Mostly consistency.

- They don't match the rest of the current theme (in terms of size, colors, gradients, shadows, style, etc)
- They were [not as consistent](https://user-images.githubusercontent.com/1984060/154384451-043fd8cd-a81d-49a8-8de5-3f9892422567.png) at different sizes
- They were not being used for quite some time as the names [did not match](https://user-images.githubusercontent.com/1984060/154384467-dcd82f5f-8364-4e94-84db-8f7a32cc81e0.png) the mimetype
- Clarity. I just think the newer icons convey their meaning better
- They looked a little too much like an app icon (as opposed to file icons)
- Tying the look heavily to one app is not ideal
- This PR was accepted upstream and it's easier to maintain with them for now while doing these refreshes and upstream pulls.

This is mostly subjective of course. What I'm trying to do now is just create a newer refreshed base and get the theme to a really consistent and uniform look. The "Removed" and "Added" pics above look like two very different looks/styles that don't mesh very well (though on their own they look good, they just don't mix well in their current state). But for now I'm just focusing on keeping what is already most complete and uniform, and fixing symlinks, naming, and all that.

**Pull request merged**
