### PR TITLE
Rename battery icons, remove legacy battery icons

### PR DESCRIPTION
**Pull request by newhoa**
Renames the battery icons to use Upower icon names.
Xfpm has used these since 2015 so I think anything
else can be considered legacy and safe to remove.

Removes legacy xfpm and gpm battery icons and symlinks.

Fixes issue where Power Manager -> Line Power didn't use
the right icon.

### CODE REVIEW

**Comment by ochosi** [comment]
Same as with the other big PR - do you know what Mate uses? I don't wanna completely break the theme for users that switch between DEs (even your cleanups are _really_ appreciated!)

**Comment by newhoa** [comment]
After checking the other DEs on this one, this PR fixes issues in Xfce, Budgie, and Cinnamon. So improvements there.

MATE uses the Upower names for their panel (they use symbolic icons) so it's an improvement there too. But when you go to Panel > Power Indicator > Click > Battery it provides a window with power/battery info. Here they still use the `gpm-` prefixed icons.

I'm going to open an Issue on mate-power-manager and bring this up. I'd consider it an issue on their part since they've switched some icons to the standard naming but not all. And just looking briefly at the code it looks like they may have intended to use them in all places but aren't.

Let me know what you'd like me to do with this one. They do provide fallback icons with the app so it doesn't appear really broken or without icons or wrong sizes or anything. And it doesn't seem like a thing people would see often (most probably would never). Not sure if it's worth adding 100s of symlinks back in but I'm not sure.

**Comment by newhoa** [comment]
Just a followup. Looks like the gpm- ones are only used at 48px. So maybe I can add those back in and leave out the rest?

**Comment by newhoa** [comment]
Switched this to draft till I figure out the MATE thing. It's not as simple as my last reply. Their icon preference/fallback for this is very confusing.

**Comment by newhoa** [comment]
@ochosi Can I get your input on this?

In its current state, this PR is good for Xfce, Gnome, Cinnamon as they all use the same names. It is also an improvement for the MATE status indicator as it will now use a symbolic icon which is easier to see and preferable to the "fake" symbolic icons that the `gpm-` ones were.

*If* I add the `gpm-` icons back in for the mate-power-statistics app, it will force the MATE status indicator/tray icon to go back to a non-symbolic icon.

Unfortunately the mate-power-manager the tray status/indicator and the power statistics window use and prefer different icon names (details [here](https://github.com/mate-desktop/mate-power-manager/issues/377#issuecomment-1120506028)).

So the choice is

1) Keep this PR as it currently is and have MATE have a nicer more legible tray/status indicator (and let mate-power-statistics use its own provided icons).

2) Add the `gpm-` icons back in and have icons for mate-power-statistics but have a less legible tray icon.

Personally I think Power Statistics won't be used often or by many and it would be better to just use the Upower names and have symbolic icons for their tray which will be more useful and seen all the time. It's also good for all the other DEs and makes elementary-xfce slimmer and more manageable.

Let me know what you think. Thanks.

**Comment by ochosi** [comment]
Thanks for the thorough analysis! I read through the related Mate issues you submitted and believe it should be fixed in their components, not worked around by icon themes.
Also, as you say, the tray/statusnotifier is visible at all times whereas the stats are only visible _sometimes_. For that the fallback icons are probably good enough.

So I would suggest we merge this as is!

**Pull request merged**
