### PR TITLE
Chenge doc location

### PR DESCRIPTION
**Pull request by DeadMozay**
It makes no sense to keep the same files in different directories, and this will simplify building packages for maintainers

### CODE REVIEW

**Comment by ochosi** [comment]
@DeadMozay  Are you a packager?
I think the reason why we set things up as they are is because every theme then has the author, license, etc info in their folder, as they also get installed to different folders.
I'm not a packager, but I'm not sure if dropping those files is really helpful.

@bluesabre, @jbicha: wanna weigh in?

**Comment by DeadMozay** [comment]
when packing in RPM packages duplicate files are considered errors

**Comment by ochosi** [comment]
Interesting, I wasn't aware of that. If there are no concerns from the others I'm of course ok with dropping these files.

Would symlinking be ok for rpms?

**Comment by DeadMozay** [comment]
symlinking are allowed, this will be the best solution

**Comment by maugalli** [comment]
Hello I packaged with @DeadMozay the RPM for openSUSE.
We bypassed the issue using a patch file for now. I also believe that adding the correct symlinks in the source root path is likely to solve the problem. The files needed in the root would be the most up to date CONTRIBUTORS, LICENSE, AUTHORS and README.md

PS: I created issue #134 but I will close it

**Comment by jbicha** [comment]
On Debian, it is unnecessary to install the `LICENSE` file because Debian Policy already requires that a copyright file be provided in the Debian packaging which is then installed in a standard location for all users. Depending on how up-to-date and complete that copyright file is, the `AUTHORS` and `CONTRIBUTORS` file may be unneeded too.

(Let be more precise: Debian very, very strongly wants every source tarball to include a `LICENSE` or similar statement of license. That file just doesn't need to be **installed** in the binary packages.)

It's not a big problem since [it's easy](https://salsa.debian.org/xfce-extras-team/elementary-xfce/blob/master/debian/rules) for the Debian package to remove the extra `LICENSE` files (or other files) to avoid a (very minor) [Lintian warning](https://lintian.debian.org/tags/extra-license-file.html)

**Comment by maugalli** [comment]
Please allow me clarify something as well. openSUSE has a centralized and specific location for all the doc files:
/usr/share/doc
/usr/share/doc/packages/
/usr/share/licenses

The spec file gives instructions to fetch and install  the doc and license files in the correct location, through the macros %doc and %license. However such doc files need to be in the root path of the source archive for this to happen automatically. If they are not, you need to give instructions manually through the spec file, adding lines to prevent errors. or through patches. It can be a bit tricky and not very polished. 

In addition as mentioned by @DeadMozay  multiple duplicate files in different sub directories will trigger errors, but it could possibly be averted by using symlinks from one of the subfolders to the root path.

https://build.opensuse.org/package/show/X11:xfce/elementary-xfce

**Comment by DeadMozay** [comment]
Symbolic links must be from the root directory to subdirectories. So be right

**Comment by ochosi** [comment]
@DeadMozay Do you wanna update your PR to do symlinks or shall I just push the change to master?

**Comment by DeadMozay** [comment]
I have little acquaintance with git, I can do something wrong

**Comment by ochosi** [comment]
Thanks @DeadMozay

**Comment by maugalli** [comment]
Thank you very much both for the commit and merge!

**Pull request merged**
