### PR TITLE
Replace find action icon

### PR DESCRIPTION
**Pull request by newhoa**
Replaces current monochrome `edit-find` icon
with one more similar to other action icons.

This should make the find/search icon easier to see
in both light and dark gtk themes, and fix the issue of
needing unique icons for the light and dark icon theme.

Let me know what you all think of the style/colors, etc.
This would effect the Appfinder icon as well as find,
search, search and replace icons in toolbars, menus, etc.

e-xfce-edit-find-new

### CODE REVIEW

**Comment by ochosi** [comment]
Please update the search and replace icon too, then this is good to go!

**Comment by newhoa** [comment]
> Please update the search and replace icon too, then this is good to go!

Wow thanks for the quick reply! Will do! Just wanted to make sure it was okay before I did all the sizes and everything. Thanks!

**Comment by ochosi** [comment]
I try ;)
Awesome, looking forward to it :)

**Comment by newhoa** [comment]
@ochosi This and the other battery PR should be ready. The checks are failing though.

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/d/dbus/libdbus-1-dev_1.12.16-2ubuntu2.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

Looks like `libdbus-1-dev_1.12.16-2ubuntu2.1` got a version bump to `libdbus-1-dev_1.12.16-2ubuntu2.2` and for some reason it's not using the newer package?

**Comment by ochosi** [comment]
That seems to be a problem with the container and the repo, I'm trusting that you checked for dangling symlinks locally ;)

**Pull request merged**
