### PR TITLE
make nm-device-wired icon 16px match 22px style

### PR DESCRIPTION
**Pull request by Mau-G**

### CODE REVIEW

**Comment by ochosi** [comment]
Why is elementary-xfce/panel/16/nm-device-wired.svg in bright colors instead of dark?

**Comment by Mau-G** [comment]
@ochosi It’s  icon for the dark theme.

**Comment by Mau-G** [comment]
> Why is elementary-xfce/panel/16/nm-device-wired.svg in bright colors instead of dark?

I don't know what happened.... I screwed up the icons apparently. I will fix soon

**Comment by Mau-G** [comment]
@ochosi in case you missed it I fixed the icons

**Comment by Mau-G** [comment]
@ochosi shall we merge this or discuss further the gradient / shadow further first?

**Pull request merged**
