### PR TITLE
Add programming language mimetypes

### PR DESCRIPTION
**Pull request by newhoa**
Wasn't sure what to use for Perl (see [this article](https://dev.to/thibaultduponchelle/the-perl-complex-topic-of-logos-3161)). Some of these use CC-BY-SA content. Should I add those credits somewhere (maybe the Authors file)?

Let me know if these look okay. I just did the 64px ones so far, will have to work on the others over time. Thanks.

Current:

current

Proposed:

proposed

Added
- C#
- C++
- D
- Fortran
- Groovy
- Haskell
- Kotlin
- Lisp
- Pascal
- Rust
- Sass/Scss
- Scheme
- Yaml

### CODE REVIEW

**Comment by ochosi** [comment]
These look awesome - thanks so much! I'm sure users will appreciate this (I know I do)

**Comment by ochosi** [comment]
@newhoa I'd like to do an upstream release soon so it can be picked up by distros that ship releases. Do you want to finish this first/soon? If so, I'm happy to wait.

**Comment by newhoa** [comment]
@ochosi I'll be able to finish this up on Sun if it's okay to wait on a release till then. If not that's okay too, it can get in next time.

**Comment by ochosi** [comment]
@newhoa No rush! Just ping me whenever this is ready, I'm happy to wait.

**Comment by newhoa** [comment]
@ochosi This should be ready for review.

Hopefully adding the license info in the Authors file for a few of the logos was okay, let me know if I need to add the licenses themselves or if a link like that is okay (or if it's okay to use them at all in this theme -- I believe it is).

The Rust logo looks a little different at 16px. I tried using the circle/gear (pic below), but it just wasn't very legible (but it was more consistent). Let me know what you think about that one.

e-icon-16-rust

**Review by ochosi — APPROVED** [review]
Extending the `AUTHORS` file sounds good.

I also agree with the R over (R). Legibility > consistency (in most cases).

**Pull request merged**
