### PR TITLE
App icons: Remove unused, rename misnamed

### PR DESCRIPTION
**Pull request by newhoa**
Sorry, this is a pretty big PR. Didn't realize till the end, but it required shuffling symlinks around on many changes so it's kind of hard to split it up at this point. If needed let me know and I can try and find a better way to split it up.

---

Gnome Settings now uses a text-only list and incorporates
power, session, display, and sound (and more) related settings.
So these icons are no longer needed. I checked Adwaita history
before removing these and was able to find deprecation info on
almost all of them.

Some of these were linked from or to the `categories`,
`actions` folders as well as the elementary-xfce-darker
variant folder so icons in those locations  were
re-symlinked/moved/removed when needed.

Removed unused Gnome icons
- gnome-audio and gnome-volume icons
- gnome-display
- gnome-panel icons
- gnome-settings icons
- gnome-status
- gnome-unknown
- gnome-web-browser
- accessibility-directory
- administration
- force-exit

Removed dead project icons
- Adobe Reader
- epiphany webkit and gecko
- gnomebaker
- xchat-gnome
- xchat-mini
- xchat

Updated Gnome app names
- Calculator
- Epiphany
- Evince
- Gedit
- Power Manager
- Screenshot
- Settings
- Sound Recorder
- System Monitor
- Weather

Updated other app names
- Hexchat
- Orage Globaltime

---

Edit:
For reference, these icons were removed as they were only used for some of the gnome-specific stuff (they were not symlinked to anything else and not used by gnome anymore). Just wanted to add this in case the assets need to be used for something else in the future:

gnome-inhibit-applet
gnome-panel-force-quit
gnome-session-hibernate
gnome-session-switch

e-xfce-apps-removed-v1

### CODE REVIEW

**Comment by ochosi** [comment]
Wow, this is indeed quite bit :)

I'm wondering if Mate (or Cinnamon?) use some of these icons as they "inherited" a bunch of the old Gnome stack and I'm not sure if all their icons have been renamed... If you have the time, could you take a look?

**Comment by newhoa** [comment]
> Wow, this is indeed quite bit :)
> 
> I'm wondering if Mate (or Cinnamon?) use some of these icons as they "inherited" a bunch of the old Gnome stack and I'm not sure if all their icons have been renamed... If you have the time, could you take a look?

Okay...

Good news is that this doesn't change anything in MATE, Cinnamon, or Budgie except fix the Gnome apps used by Cinnamon and Budgie. It doesn't break or worsen anything. So this PR should be good.

Bad news is that MATE and Cinnamon have switched away from not only Gnome naming, but also standard naming. So they each have their own specific set of icons now (prefixed with mate-, cinnamon-, or cs-). So this theme doesn't look too great on either. This has nothing to do with this PR, just the theme in general.

I made a list of icon names for those DEs and can make an Issue if you'd like that to be worked on in the future (not something I'm focused on right now though).

**Comment by ochosi** [comment]
Ok cool, thanks for checking and for putting together a list - that sounds really great! Shall we enable the wiki in this github project so you can paste it there or do you wanna put it in a github issue instead?

I was afraid this type of fragmentation would happen, haven't checked up on none of these DEs lately...

As soon as the PR is mergeable (currently conflicting) again I'm happy to merge!

**Comment by newhoa** [comment]
Fixed the conflicts, this one should be ready!

And about the icon list, I'd rather just add it to an issue if that's okay.

**Comment by ochosi** [comment]
Hm, GitHub seems to think otherwise - there are still conflicts :/

**Comment by newhoa** [comment]
I thought I fixed the last two (I force pushed it, idk if that messes things up for others). It says `This branch has no conflicts with the base branch` for me so I'm not sure what I can do. Maybe close this and resubmit it?

**Comment by ochosi** [comment]
Hm, only the rebase option seems to fail. Squashing and merging seems to work, so I'll go ahead and do that then.

**Pull request merged**
