### PR TITLE
Status: Make symbolic wifi icon larger

### PR DESCRIPTION
**Pull request by newhoa**
New symbolic wifi icon to make size of status / systray icons more consistent. Making it taller requires changing the shape a bit so it's not quite as curvy, but it looks more consistent.

Addresses part of #152

Current:
wifi-symbolic-current

Proposed:
wifi-symbolic-prop1

---

In this PR the VPN Lock currently has no color class:
wifi-prop-noclass

Any thoughts on adding a color class or leaving it normal? The non-symbolic version uses a yellow/orange color. Success/green and Warning/orange as examples:

wifi-prop-success wifi-prop-warning

### CODE REVIEW

**Comment by ochosi** [comment]
How do these (and their sizes) fare against upstream? I feel that the wifi icon's proportions are a bit off.

**Comment by newhoa** [comment]
Upstream hasn't addressed the sizing issues so they still use the original icon.

Anything specific about the proportions?

I actually like the more curved look of the original one more. But when making it longer the same curves couldn't be kept because they would clip (the original is already 15px so you couldn't expand them much more keeping the same angle).

I gave it another shot and tried to get a little closer to the original curves with maybe better spacing? The lines are I think slightly thicker though.

Initial PR:
network-wireless-signal-excellent-symbolic
network-wireless-signal-excellent-symbolic-light



2nd try: 
network-wireless-signal-good-symbolic
network-wireless-signal-excellent-symbolic-prop2-light


Lol they look identical when posted alone like this, but the 2nd try does have better spacing, angles, and a little higher of a curve.

**Comment by ochosi** [comment]
Nice work on the 2nd try - I think I can make out the improvement quite clearly!
Let's go with that version

**Comment by newhoa** [comment]
> Nice work on the 2nd try - I think I can make out the improvement quite clearly! Let's go with that version

Updated this one using the newer style, so if that's still okay this one should be good to go. Let me know what you think! Thanks!

**Comment by newhoa** [comment]
@ochosi I wasn't sure if you wanted me to merge only that last PR or continue merging some of these other PRs? I don't want to overstep my permissions or anything so, if you are okay with my merging more, just let me know if you have any guidelines or circumstances where you wouldn't want me doing other PRs. Thanks!

I think I can at least go ahead and do this one since you already said okay to the latest revision here.

**Comment by ochosi** [comment]
I trust you to merge what you consider ready!

**Pull request merged**
