### PR TITLE
Make window-close visible in dark and light themes

### PR DESCRIPTION
**Pull request by newhoa**
Trying to ditch the monochrome close icon and make it more visible in light and dark themes.

Let me know what you think about the shape/design and color. If the red is too loud or anything else. And also if I should do the other sizes in the same style.

### CODE REVIEW

**Comment by ochosi** [comment]
I'm fully aware of the problem and it reflects the change of the search glass icon I guess. I'm not sure if that's not a bit "too loud" though with respect to the rest of the icons.

As an alternative to your proposal we could add the existing icon to the -dark sub-theme, which still contains a lot of those monochrome faux symbolic icons and at the same time try to come up with something that'll work on all backgrounds. Thoughts?

**Comment by newhoa** [comment]
> I'm fully aware of the problem and it reflects the change of the search glass icon I guess. I'm not sure if that's not a bit "too loud" though with respect to the rest of the icons.
> 
> As an alternative to your proposal we could add the existing icon to the -dark sub-theme, which still contains a lot of those monochrome faux symbolic icons and at the same time try to come up with something that'll work on all backgrounds. Thoughts?

I don't mind waiting for something that works all around. I'd rather do that than shuffle things around with the variants (trying to work on removing or slimming those down now).

I know moving away from the faux symbolic icons is best, but maybe that's the solution to the close icon without making it to loud. How about the proposal style/shape but monochromed? Seems to work on dark and light themes:
light dark

**Comment by ochosi** [comment]
Yup, that's a good direction. Let's do that - and hopefully most apps switch to the symbolic icon name anyway... (Seeing the difference might actually help with the switch)

**Review by ochosi — APPROVED** [review]
:heart:

**Pull request merged**
