### PR TITLE
elementary XFCE cursors and updates

### PR DESCRIPTION
**Pull request by sergioad**
Hello here is my commit, it is mostlly a re-work of the icon theme respecting your guidelines BUT adding some new add ons like new icons provided by the elementary fans (8 in total being transmission remmina Corebird (the elementary tweetdeck icon renamed) Steam Minetest Skype and other more) added new gaming controller based emulators icons (gnuboy vbam zsnes snes9x fceux fakenes gens gens-gs and two more allready working icons, there is one what not correctlly named) and I have updated many other icons, the icon theme will cover in a better way everything, finally I have added a light panel and dark icons variant to it, I will submirt new commits right on this pull request because is very hard to open another more

### CODE REVIEW

**Comment by sergioad** [comment]
@ochosi here is the pull request, I hope see it on the Xubuntu and Fedora repos soon :smile:

**Comment by ochosi** [comment]
Thanks for the merge-request.
Wowza, this is really too big to be reviewed at a time. Could you split this up into more digestable portions please?
Ideally do one merge-request per contribution, e.g. one for the light meta theme/s and one for the additional icons.

Btw, I can tell you in advance that certain icons (like Skype) cannot find their way into the icon-theme for licensing issues.

**Comment by Foggalong** [comment]
> I can tell you in advance that certain icons (like Skype) cannot find their way into the icon-theme for licensing issues

Can you expand on that? I wasn't aware this was a problem :(

**Comment by sergioad** [comment]
@Foggalong I opine the same thing

**Comment by ochosi** [comment]
There were issues with Skype icons shipped in Ubuntu's humanity icon-theme (afaik Skype got in touch with Canonical directly), so I won't touch that with a 10-foot pole. Not worth it.
(For icon-themes that aren't shipped by default in a bigger distro, those might "fly under the radar", but I'm not taking any risks.)

**Comment by Foggalong** [comment]
Oh wow! I didn't know about that, thanks for letting me know

**Pull request closed without merging**
