### PR TITLE
Add 'split view' icon for Thunar 4.17 toolbar

### PR DESCRIPTION
**Pull request by newhoa**

### CODE REVIEW

**Comment by ochosi** [comment]
A screenshot in context would be nice!
Are there similar icons upstream or in other DEs?OSs?

**Comment by newhoa** [comment]
> A screenshot in context would be nice! Are there similar icons upstream or in other DEs?OSs?

e-xfce-thunar-dual

This is one of the [new default icon-view toolbar items added to Thunar](https://gitlab.xfce.org/xfce/thunar/-/commit/e8a3ff761cea609c37258caa42daccc86a872df7).

It's not a very common icon and I think is used in more of a pdf context (view page side by side), so a few themes have it (Papirus, Breeze, Adwaita, Yaru). Yaru and Adwaita both use the [same style](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/scalable/actions/view-dual-symbolic.svg), every other theme that provides it seems to use a [square with a line in the middle](https://github.com/KDE/breeze-icons/blob/master/icons/actions/16/page-2sides.svg).

**Comment by ochosi** [comment]
I'd also go for a more simplistic version. The window bar/toolbar at the top doesn't help I htink (none of the other view icons have that) and the rippled border also suggest something is torn apart or so.

**Comment by newhoa** [comment]
Centering things is hard with such small icons. For it to be 1px and match the rest of the icon, centering it puts it out of grid alignment (11.50 on a 24px canvas), so it needs to be to the left or right 1px which looks a bit off to me (although I guess split view can be adjusted to be smaller on one side):

image

Using a 2px width line so it centers looks worse, I think. I really dislike it:

image

If that first one, slightly off-center, looks okay, I can update to use that one. Or if you have any other ideas let me know. Thanks.

**Comment by ochosi** [comment]
Yeah, the 2px line doesn't look great. I think the simple one is great - even if it's slightly off-center!

**Comment by newhoa** [comment]
Ok, updated this one, should be good. Thanks!

**Pull request merged**
