### PR TITLE
Refreshed 16px dark panel icons and added some new ones

### PR DESCRIPTION
**Pull request by Mau-G**
Removed gradients like upstream did and synced network icon

I also made some new icons (see screenshot) although I am not sure they are actually used:

newicons

### CODE REVIEW

**Comment by tttech-steinbeiss** [comment]
The icons in the screenshot look nice! I haven't had time yet to check the removal of the gradient, but I trust you to merge the pull request ;)

**Comment by ochosi** [comment]
The icons in the screenshot look nice! I haven't had time yet to check the removal of the gradient, but I trust you to merge the pull request ;)

**Comment by Mau-G** [comment]
ok thank you I will merge. I have a few more to add first

for mail-watch-plugin:
Screenshot_2020-02-16_18-36-12

tomboy or xfce4-note-plugin:
Screenshot_2020-02-16_18-42-55

dropdown xfce4-terminal:
Screenshot_2020-02-16_18-48-12

**Comment by Mau-G** [comment]
Superseded by #175

**Pull request closed without merging**
