### PR TITLE
steam icon

### LINKED ISSUE #76: Steam icon
I was chatting with ochosi in freenode. I don't know how to commit file, so I have create and issue. Attaching archive with 4 icons for steam app
https://www.dropbox.com/s/8yxspi9vow2gcn3/elementary-xfce.zip?dl=0

### PR DESCRIPTION
**Pull request by Yanpas**
Closes #76

### CODE REVIEW

**Comment by ochosi** [comment]
A few notes:
 * Icons for the panel go in the panel/ subfolders
 * the 22px icon is in fact 16px
 * the icons don't have the correct margin and shadow (check other panel icons for reference)
 * several lines in the icons aren't perfectly aligned to the grid, so those parts look a bit blurry.

**Comment by Yanpas** [comment]
@ochosi I've reworked icons, https://www.dropbox.com/s/kyo14hai38ruqtb/steam.zip?dl=0 . Take a look. 
* Size matches name of a folder
* Margins on, shadows were made like the dropbox icon has
* Nodes are touching grid lines

BUT, Steam icon placed to panel folder won't be recognized by steam. Steam stores two icons in apps folder (steam and steam_tray_mono)

**Comment by Yanpas** [comment]
[steam.zip](https://github.com/shimmerproject/elementary-xfce/files/233468/steam.zip)

**Comment by ochosi** [comment]
Hey, alright, that looks a lot better. The main downside of adding those icons is that Steam won't recognize them as you pointed out.
Not being sarcastic, what would be the benefit of shipping the icons if they're not used by Steam?

**Comment by Yanpas** [comment]
It seems that I've gorgot to do something half year ago. Steam tray icons is successfully recognized (in this screenshot from Mint theme)

**Comment by Foggalong** [comment]
@ochosi If the user is using [this program](https://github.com/bil-elmoussaoui/Hardcode-Tray) then the tray icon can still be themed

**Comment by ochosi** [comment]
@Yanpas Alright, I will go ahead and merge this in then. Could you please clarify: is the .zip file the latest version or the files in your merge-request? (Ideally you would update your merge request so I can do a clean merge...)

**Comment by Yanpas** [comment]
I will update commit in a second :) GH now supports commit squashing, so I will create one more commit in my branch.

**Comment by Yanpas** [comment]
I've updated. Icons were revamped. I've just got the idea of panel icons :smile: 
I guess they look cool

**Comment by ochosi** [comment]
Hrm, it's almost perfect and good to go, but the icons should actually go into the panel/ folders, not apps/.

Even if it's an application icon, it's specifically for the panel, so this is the correct place. Mind to update that commit again? :)

**Comment by Yanpas** [comment]
I thought steam would not find icons if they were in panel folder, but it seems to work. I've deleted black steam panel icon, cause there were no 32 folder. Should I add 32 folder or 9 icons is ok?

**Comment by ochosi** [comment]
Sorry I dropped the ball on this pull-request. Reviewed and merged now!

(better late than never)

**Pull request merged**
