### PR TITLE
updated software-updater icons to match symbolic icons color codes

### PR DESCRIPTION
**Pull request by Mau-G**
software-updater non symbolic icons to use the same color codes as the symbolic icons, defined by class "warning" for update available and "error" for urgent updates

### CODE REVIEW

**Comment by ochosi** [comment]
While that makes sense we'd probably have to do this change to other icons too to remain consistent.
Currently a lot of icons don't exactly look the same in symbolic and non-symbolic variants, although I agree that in this case it may make sense.

**Comment by Mau-G** [comment]
I mean we can work the other way instead of merging this PR which would be to change the colors used for the roles. However I am not sure where the colors are defined.

**Comment by ochosi** [comment]
The colors are defined in the Gtk theme, so there isn't much we can do. That's why this consistency is something very relative and dependant on the actual theme selection (same as with fg color of symbolic icons btw)

**Comment by Mau-G** [comment]
> The colors are defined in the Gtk theme, so there isn't much we can do. That's why this consistency is something very relative and dependant on the actual theme selection (same as with fg color of symbolic icons btw)

ok gotcha. At least with Greybird, Adwaita and Mint themes it seems to follow the same "yellow" and "red" colors so it would imo make sense in this case to merge so to keep the consistency of the colors between the updater non-symbolic and symbolic icons.

**Comment by ochosi** [comment]
Alrighty let's do that then

**Pull request merged**
