### PR TITLE
Apps: New icon for Ubiquity (Xubuntu Installer)

### PR DESCRIPTION
**Pull request by newhoa**
@bluesabre and @ochosi, Let me know if this new Ubiquity/Xubuntu Installer icon is okay and I can work on other sizes. Not sure if making a distro-specific icon for a potentially distro-agnostic installer is okay, but I think at this point Xubuntu is the only distro using this theme as default and using the Ubiquity installer, so I don't think it would be seen in any other circumstance.

Currently proposing the square style:
xubuntu-install-square

Another option is the circle style:
xubuntu-install-circle

Let me know if it's okay to keep going replacing the ubiquity icon, and if so which style. Thanks!

### CODE REVIEW

**Comment by ochosi** [comment]
I think it's ok to include. Otherwise we could always separate them out in a folder or branch.

I would prefer the circle. The other one also looks good but might not be obvious.

**Comment by bluesabre** [comment]
I agree. The circle style looks great, matches the current installer icon (but is better), and will survive if the new Flutter installer changes it's layout in a way that removes the progress dots.

**Comment by newhoa** [comment]
Ok, went with the circle and added all the sizes. Should be good to go if you all want to check it over.

**Comment by bluesabre** [comment]
This looks good to me. Let's get it merged!

**Pull request merged**
