### PR TITLE
[UPDATED] Commit for the elementary XFCE icons

### PR DESCRIPTION
**Pull request by sergioad**
Hello here is the updated icons again but now pushed one section per commit, the skype icon is not any problem, you can merge it; why? well the Numix icons has it and many other non free software icons, BTW I have here some screenshots about the results

captura de pantalla - 160215 - 11 57 07
Accesories

captura de pantalla - 160215 - 11 57 26
Graphics

captura de pantalla - 160215 - 11 57 42
Internet

captura de pantalla - 160215 - 11 58 10
Multimedia

captura de pantalla - 160215 - 11 58 25
Office

captura de pantalla - 160215 - 12 01 52
Games

captura de pantalla - 160215 - 11 58 57
Emulators and the new Freya terminal icon

### CODE REVIEW

**Comment by ochosi** [comment]
Ok, this is still *one* merge-request, but fine, I'll comment on the individual commits here.

The Fedora distributor logos can only be included if they are SVG (as the whole theme is, with very very few exceptions that I've tried to eradicate). This is a question of maintenance. Also, I think this is a perfect candidate for being shipped as a distro-specific patch.

The -light variant seems to be the same as -darkest, at least I don't see any difference. Could you explain that please?

The cursor theme has only been added upstream a few days ago, I'm still reviewing whether I want to merge that.

The category commit adds category icons that only exist in one size and that aren't widely used. I'm still not convinced I want to merge those. My general policy is that I only merge new icons of which I have all sizes (or I create the remaining sizes).

The aforementioned problem of missing sizes very much applies to the final commit "updated apps". A lot of those apps (like the new calculator) only exist in hi-res version, so it'll look really bad in a menu with 16px icons. Many of those icons I haven't merged from upstream yet because I haven't had the time to draw the additional sizes.
Some I have rejected for other reasons, for instance the new settings manager icon. This single on/off switch just doesn't cut it for me really.

**Comment by sergioad** [comment]
Can you help me to fix that? I am not a graphical designer, I made a lot of work to get this result

About the light variant is based on the dark variant but inheriting the elementary-xfce icon theme having only dark icons on the panel and toolbar, ideal for light themes (you can check it on action on my images), it fits perfectlly with similar themes to Numix frost light or Vertex light

about the categories yes, the main upstream icons has one size specific icons sadlly

The cursor theme is awesome, it can be (hopefully) good for you

The distributor logo fedora icons are SVGs are not?

And finally the apps you are correct, there are hi resolution (32 48 64 and 128 pixels)

If you get the posibility please help me with the weak points of my commit

**Comment by ochosi** [comment]
Frankly, I don't think there is much I can help you with specifically here. I'm already doing everything to get as many icons from upstream while adhering to my principles of having all sizes...

The cursor theme will be reviewed separately when I have time.

And yes, the fedora icons are png.

Please test the darkest-variant of elementary-xfce, it does exactly what you want and what your -light is.

**Comment by sergioad** [comment]
@ochosi I will try it, by the way check the apps what I have updated, there are new icons for Gnome music photos totem viewnior eog Minetest Remmina and many others, do not drop the pull request, because there are lots of usefull apps

**Comment by sergioad** [comment]
@ochosi well yes it is pretty the same, do not merge the light variant

**Comment by ochosi** [comment]
Closing this as obsolete.

**Pull request closed without merging**
